### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly

### ISSUE THREAD

**Issue by sdcampbell** [Z4kSec/Masky#4]
I needed to obfuscate Masky.exe to bypass antivirus. In file impersonate.cs I changed `if (accountName.ToUpper().Contains("NT AUTHORITY\\")` to `if (accountName.ToUpper().Contains(ReverseString(badname))`, and of course I added the ReverseString function and a variable for the reversed string. This bypassed antivirus detection. :)

When I run the masky Python module with debugging enabled, or run Masky.exe directly on a target system, I get a lot of errors similar to the following:

```
System.IO.FileNotFoundException: Could not load file or assembly 'Interop.
CERTENROLLLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or o
ne of its dependencies. The system cannot find the file specified.        
File name: 'Interop.CERTENROLLLib, Version=1.0.0.0, Culture=neutral, Publi
cKeyToken=null'                                                           
   at Masky.Cert.CreateCertRequestMessage()                               
   at Masky.Cert.GetCertUser()                                            
   at Masky.Impersonate.ExecuteActionWithToken(Action action, IntPtr& Newh
ProcToken, IntPtr& currentProcHH, Boolean revert)
```
I don't get any errors if I simply run Masky.exe without any arguments. I don't really know if I broke Masky, or if it's an issue with the installed .Net version on the target systems. 

OS info (target system):

```
OS Name:                   Microsoft Windows Server 2012 R2 Datacenter    
OS Version:                6.3.9600 N/A Build 9600
```

I checked the installed .Net versions (on the target system) and see the following:

```
C:\>reg query "HKLM\SOFTWARE\Microsoft\Net Framework Setup\NDP\v4" /s

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Net Framework Setup\NDP\v4\Client
    Version    REG_SZ    4.8.03761
    CBS    REG_DWORD    0x1
    TargetVersion    REG_SZ    4.0.0
    Install    REG_DWORD    0x1
    InstallPath    REG_SZ    C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
    Servicing    REG_DWORD    0x0
    Release    REG_DWORD    0x80eb1

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Net Framework Setup\NDP\v4\Client\1033
    Version    REG_SZ    4.8.03761
    CBS    REG_DWORD    0x1
    TargetVersion    REG_SZ    4.0.0
    Install    REG_DWORD    0x1
    Servicing    REG_DWORD    0x0
    Release    REG_DWORD    0x80eb1

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Net Framework Setup\NDP\v4\Full
    Version    REG_SZ    4.8.03761
    CBS    REG_DWORD    0x1
    TargetVersion    REG_SZ    4.0.0
    Install    REG_DWORD    0x1
    InstallPath    REG_SZ    C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
    Servicing    REG_DWORD    0x0
    Release    REG_DWORD    0x80eb1

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Net Framework Setup\NDP\v4\Full\1033
    Version    REG_SZ    4.8.03761
    CBS    REG_DWORD    0x1
    TargetVersion    REG_SZ    4.0.0
    Install    REG_DWORD    0x1
    Servicing    REG_DWORD    0x0
    Release    REG_DWORD    0x80eb1
```

**Comment by sdcampbell** [comment]
This is the part I changed, in impersonate.cs:
![error](https://user-images.githubusercontent.com/10532268/204892919-d6a47320-8864-4df2-bef2-ea43345ad6df.jpg)

**Comment by sdcampbell** [comment]
I thought that maybe I was missing some Nuget packages, so I tried right clicking on the solution and choosing "Restore NuGet Packages", but the output says: "All packages are already installed and there is nothing to restore.".

**Comment by sdcampbell** [comment]
I found a directory excluded by antivirus and uploaded the precompiled version of Masky.exe and ran it there and it worked without error. I still want to figure this out so that I can update the CrackMapExec module before I use it on other pentests.

**Comment by Z4kSec** [comment]
Hi @sdcampbell,

Thanks for these details!

Masky rely on the usage of two external DLL used mainly to create certificate requests for the ADCS. Both of them are located [here](https://github.com/Z4kSec/Masky/tree/master/agent/Masky/dll).

I recommend to open the project within Visual Studio via the [Masky.sln](https://github.com/Z4kSec/Masky/blob/master/agent/Masky.sln) file. By doing this, you will be able to easily modify the code and then recompile the agent executable.

Otherwise, you could also use the `dotnet publish` command line tool to rebuild the project. The goal is to ensure that both non-native DLL are added while compiling the agent. 

Note that the latest version (0.1.2) provides a `-e` and `--exe` parameter to load an obfuscated or packed Masky agent easily. The CME module does not include this feature for the moment.

**Comment by sdcampbell** [comment]
When I use the -e option and provide the path to my obfuscated copy of Masky.exe, using the -v option I see:

`System.IO.FileNotFoundException: Could not load file or assembly 'Interop.CERTENROLLLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.`

and...

`System.IO.FileNotFoundException: Could not load file or assembly 'Interop.CERTENROLLLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.`

The only way I can get Masky to work is to zip up Masky.exe with all of the required dll's and unzip them in the same directory on the target system before running. If I run masky from Linux, I either get stopped by antivirus or when using the -e option I have the missing dll errors. 

Thank you

**Comment by sdcampbell** [comment]
I noticed that the Masky Visual Studio project is using dnMerge, yet when I edit (obfuscate) it and rebuild, my exe is only 22Kb compared to 271Kb for the precompiled version of Masky.exe that ships with your project. It seems that despite including dnMerge, I suspect that the dll's aren't being included in the exe.

**Comment by sdcampbell** [comment]
I think I found the answer. On the dnMerge Github issues, it says "debug vs release". I changed it to release, rebuilt, and the exe size is now 271kb. I'll test and come back and close this if fixed.
